type: "crud-v1"
entityName: Cliente Pet
entityNamePlural: Clientes Pet
description: Cadastro de Clientes
name: clientes_pet
readMenu: Visualizar//Clientes
createMenu: Cadastrar//Clientes
fields: 
  - nome
  - cliente_desde
  - cpf
  - rg
  - logadouro
  - numero
  - complemento
  - bairro
  - cidade
  - estado
  - pais
  - cep
  - fone
  - celular
  - e_mail
