type: "crud-v1"
entityName: Tipo de Produto
entityNamePlural: Tipo de Produtos
description: Tipo de Produtos
name: tipo_de_produtos
readMenu: Visualizar//Tipo de Produtos
createMenu: Cadastrar//Tipo de Produtos
fields: 
  - descricao
